# Generated by Django 5.2.4 on 2025-12-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_cancellation_reason_booking_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='safari_slot',
            field=models.CharField(blank=True, choices=[('morning', 'Morning (07:30-09:30)'), ('midday', 'Midday (11:00-13:00)'), ('afternoon', 'Afternoon (15:30-17:30)')], max_length=20, null=True),
        ),
    ]
