# Generated by Django 5.2.4 on 2025-12-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_safari_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total booking amount in ZAR', max_digits=10, null=True),
        ),
    ]
